GET https://fsopen-phonebook-backend.fly.dev/api/persons/

###
POST https://fsopen-phonebook-backend.fly.dev/api/persons/
Content-Type: application/json

{
    "name": "asd el loco",
    "number": "3471-2534"
}

###
DELETE https://fsopen-phonebook-backend.fly.dev/api/persons/24516642