//GET request without error
GET http://localhost:3001/api/persons
////expected ==> HTTP 200 / JSON format persons


###
//GET request with error
GET http://localhost:3001/api/person
//expected ==> "unknown endpoint"