//PUT request without error  - The ID is mannualy took from the database
PUT http://localhost:3001/api/persons/632265112edfa1ca9a7f673d
Content-Type: application/json

{
    "number": "3471-2534"
}
//expected ==> HTTP 200 / JSON format person


###
//PUT request with client-side error - The ID is mannualy took from the database
PUT http://localhost:3001/api/persons/632265112edfa1ca9a7f673d
Content-Type: application/json

{
    "sorry": "only name, no number"
}
//expected ==> HTTP 200 / JSON format person
